version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "8000:8000"
        env_file:
            - .env
        environment:
            DATABASE_URL: postgres://postgres:postgres@db/postgres
        volumes:
            - .:/usr/src/app
        depends_on:
            - db
        networks:
            - backend
        command: ['./docker/entrypoint.sh', "db:5432"]
    db:
        image: postgres:12-alpine
        ports:
            - "5432:5432"
        env_file:
            - .env
        volumes:
            - ./.dbcache/pg/data:/data/db
        networks:
            - backend
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

networks:
    backend:
        driver: "bridge"
